controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
index:
    path: /
    controller: App\Controller\ProduitController::index 

# easy_admin_bundle:
#     resource: '@EasyAdminBundle/Controller/'
#     type: annotation

app_contact_submit:
    path: /api/contact
    controller: App\Controller\ContactController::submit
    methods: [POST]
    
app_order_history:
    path: /api/order/history/{userId}
    controller: App\Controller\OrderController::history
    methods: [GET]

# _sonata_admin:
#     resource: '../src/Admin'  # <-- Change this line
#     type: sonata_admin
#     prefix: /admin

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }